### ISSUE TITLE
create .gitignore; remove cache from repo

### ISSUE THREAD

**Issue by aqw** [psyinfra/HTCrystalBall#21]
The following was likely accidentally committed to the repo:

https://github.com/psyinfra/HTCrystalBall/tree/master/tests/__pycache__

To help protect against mistakes like this, a `.gitignore` file can be used.

There is a community maintained set of language-ecosystem-specific gitignores here: https://github.com/github/gitignore/blob/master/Python.gitignore

IMO, they're a bit.... excessive, but there's lots of useful ideas in there.

**Comment by jonamfischer** [comment]
closed in b63c29ee0ad32bb699bc340d27c5d9c5294a3c76

**Comment by jonamfischer** [comment]
.gitignore is now in place
