### ISSUE TITLE
README should suggest clone over HTTP, not SSH

### ISSUE THREAD

**Issue by mathisloevenich** [psyinfra/HTCrystalBall#22]
(venv) mloevenich@juseless in ~
❱ git clone git@github.com:psyinfra/HTCrystalBall.git
Cloning into 'HTCrystalBall'...
Warning: Permanently added the RSA host key for IP address '140.82.121.4' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by aqw** [comment]
This is because you don't have an SSH key uploaded to your GitHub account.

But this does highlight that the README should not assume that the user has a github account.

**Comment by aqw** [comment]
Related to #26
