### ISSUE TITLE
Update .gitignore

### ISSUE THREAD

**Issue by nhjjreuter** [psyinfra/HTCrystalBall#24]
I'd suggest updating the `.gitignore` to cover more files. For example coverage reports shouldn't be pushed. I can recommend looking at https://github.com/github/gitignore/blob/master/Python.gitignore as it'll take potential future additions that should be ignored into account.

**Comment by nhjjreuter** [comment]
Manually include the config folder and its contents in here, as they are dynamically generated by the script.

**Comment by aqw** [comment]
`.coveragerc` isn't a report, but rather an .rc file to tell codacy how to scan the project. So that file should remain. :-)

**Comment by aqw** [comment]
In this case, a PR would be nice, so that the proposed changes are concrete, and can be discussed in context.

**Comment by nhjjreuter** [comment]
This issue has been addressed in PR #36.
