### ISSUE TITLE
htcrystalball is not installed to PATH

### ISSUE THREAD

**Issue by mathisloevenich** [psyinfra/HTCrystalBall#27]
I recognised, that after installing, your advice to call the script is just:
- htcrystalball -h

However, if I am not in a virtual environment, it's not that easy, instead I have to run the script by:

- python3 htcrystalball.py -h
or:
- ./htcrystalball.py -h

Not every user will be aware of this and they will think, something is wrong, I thought so too on the first view.

**Comment by aqw** [comment]
Did you encounter this using the pip install, or just via cloning?

**Comment by aqw** [comment]
I think this is an issue with `htcrystalball` not ending up in the path. This is most likely solved by `setup.py`.

**Comment by nhjjreuter** [comment]
This issue can be resolved by setting an entry point in `setup.py`, which I'm working on for a PR

**Comment by aqw** [comment]
#32 does that (among other things)
