### ISSUE TITLE
changing SLOTS_CONFIGURATION location should not require script modification

### ISSUE THREAD

**Issue by mathisloevenich** [psyinfra/HTCrystalBall#28]
I know that you could expect a user to look behind your code, to get a more specific use case for him.

Your advice-steps 3. and 4. are based on this idea.

I think that it would be better to integrate those changes as command line options as well, 
as I needed a bit of understanding, where to find the 
```
SLOTS_CONFIGURATION = "config/slots.json"
 ``` 
because I thought it's a command line option.

Maybe you had a more specific thought behind that, 
but I think it's better to never advice the user to touch your code,
as your script seems to be meant as a command-line tool.

**Comment by aqw** [comment]
There's a few options:
1) a command-line flag
2) environmental variable
3) search through a series of common locations (etc, home dir, etc)

These are not mutually exclusive.

**Comment by jonamfischer** [comment]
The configuration is fetched through the HTCondor API, so no static file needed anymore
