### ISSUE TITLE
Parsing a .submit file

### ISSUE THREAD

**Issue by jonamfischer** [psyinfra/HTCrystalBall#54]
To quickly predict the fitting of a job that's about to be submitted, hatch should be able to parse a .submit file and use the requirements from the file instead of input parameters. The syntax of a .submit file leads to following parameters the parser should be able to identify:

- request_memory = XX  (in MB)
- request_cpus = XX  (in cores)
- request_disk = XX  (in KB)
- request_GPUs = XX  (number of GPU units)
- queue XX  (number of jobs)

**Comment by aqw** [comment]
Should be fixed by #57.
