### ISSUE TITLE
Warning printed

### ISSUE THREAD

**Issue by aqw** [psyinfra/HTCrystalBall#55]
I get a warning each time I run `htcrystalball`.

```
❱ htcrystalball --help
/home/aqw/.venvs/htcb/lib/python3.7/site-packages/htcondor/__init__.py:48: UserWarning: Neither the environment variable CONDOR_CONFIG, /etc/condor/, /usr/local/etc/, nor ~condor/ contain a condor_config source. Therefore, we are using a null condor_config.
  _warnings.warn(message)
```

This looks to be by design. If so, then the warning message should be better formatted and help the user understand what (if anything) should be done. If there is to be a config file, they need to learn the syntax somewhere.

**Comment by jonamfischer** [comment]
So this is a built in warning of the python package. I will look up how to catch and reformat the warning message.
